=== basavesht/javaee-work-projects/bosch/standard-adapter/src/META-INF/wsdl/IntegrationConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2010 (http://www.altova.com)-->
<xs:schema xmlns="http://integration.tmp.bosch.com/validation"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://integration.tmp.bosch.com/validation">
    <xs:complexType name="values">
        <xs:sequence>
            <xs:element ref="value" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="configValues">
        <xs:sequence>
            <xs:element ref="configValue" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:element name="configValue">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="id"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="validations">
        <xs:sequence>
            <xs:element ref="validation" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="validation">
        <xs:choice>
            <xs:element ref="values"/>
            <xs:sequence>
                <xs:element ref="value"/>
                <xs:choice minOccurs="0">
                    <xs:element ref="fault"/>
                    <xs:element ref="faults"/>
                </xs:choice>
            </xs:sequence>
        </xs:choice>
        <xs:attribute ref="type" use="required"/>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="segments">
        <xs:sequence>
            <xs:element ref="segment" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="segment">
        <xs:sequence>
            <xs:element ref="configValues"  minOccurs="0"/>
            <xs:element ref="configValue" minOccurs="0"/>
            <xs:element ref="validations" minOccurs="0"/>
            <xs:element ref="fields" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>
    <xs:complexType name="messages">
        <xs:sequence>
            <xs:element ref="message" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="message">
        <xs:sequence>
            <xs:element ref="inType" minOccurs="0"/>
            <xs:element ref="outType" minOccurs="0"/>
            <xs:element ref="ackNumOfLevels" minOccurs="0"/>
            <xs:element ref="ackPrecedenceType" minOccurs="0"/>
            <xs:element ref="validations" minOccurs="0"/>
            <xs:element ref="segments" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>
    <xs:complexType name="fields">
        <xs:sequence>
            <xs:element ref="field" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="field">
        <xs:sequence>
            <xs:element ref="configValues" minOccurs="0"/>
            <xs:element ref="configValue" minOccurs="0"/>
            <xs:element ref="validations" minOccurs="0"/>
            <xs:element ref="dataTypes" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>
    <xs:complexType name="faults">
        <xs:sequence>
            <xs:element ref="fault" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fault">
        <xs:sequence>
            <xs:element ref="faultInternalCode"/>
            <xs:element ref="faultInternalMessage"/>
            <xs:element ref="faultExternalCode"/>
            <xs:element ref="faultExternalMessage"/>
            <xs:element ref="segmentName"/>
            <xs:element ref="fieldNumber"/>
            <xs:element ref="componentNumber"/>
        </xs:sequence>
        <xs:attribute ref="id"/>
    </xs:complexType>
    <xs:complexType name="dataTypes">
        <xs:sequence>
            <xs:element ref="dataType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dataType">
        <xs:sequence>
            <xs:element ref="configValues" minOccurs="0"/>
            <xs:element ref="configValue" minOccurs="0"/>
            <xs:element ref="validations" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>
    <xs:complexType name="configuration">
        <xs:sequence>
            <xs:element ref="messages"/>
            <xs:element ref="segments"/>
            <xs:element ref="fields"/>
            <xs:element ref="dataTypes"/>
            <xs:element ref="application"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="application">
        <xs:sequence>
            <xs:element ref="faults"/>
            <xs:element ref="configValue" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="configValues" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="customerId"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="customerId">
        <xs:restriction base="xs:string">
            <xs:enumeration value="VA"/>
            <xs:enumeration value="MCKESSON"/>
            <xs:enumeration value="SA"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MANDATORY"/>
            <xs:enumeration value="VALID_VALUE"/>
            <xs:enumeration value="FIELDLENGTH"/>
            <xs:enumeration value="DATE_FORMAT"/>
            <xs:enumeration value="DATE_CHECKER"/>
            <xs:enumeration value="MULTIPLE_SEGMENTS"/>
            <xs:enumeration value="VA_MPI_CONSISTENCY"/>
            <xs:enumeration value="PATTERN"/>
            <xs:enumeration value="MISSING_IDENTIFIER"/>
            <xs:enumeration value="VA_MISSING_NAME"/>
            <xs:enumeration value="VA_DFN_FACILITY"/>
            <xs:enumeration value="VA_ID_CONSISTENCY"/>
            <xs:enumeration value="VA_PID_COUNT"/>
            <xs:enumeration value="VA_SERVICE_FACILITY_MAPPING"/>
            <xs:enumeration value="UNSUPPORTED_TRIGGER"/>
            <xs:enumeration value="MISSING_MSG_ACK"/>
            <xs:enumeration value="PING_MESSAGE"/>
            <xs:enumeration value="QUERYCODE"/>
            <xs:enumeration value="QUERYTYPE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attribute name="type" type="type"/>
    <xs:attribute name="id" type="xs:string"/>
    <xs:element name="values" type="values"/>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="validations" type="validations"/>
    <xs:element name="validation" type="validation"/>
    <xs:element name="configValues" type="configValues"/>
    <xs:element name="segments" type="segments"/>
    <xs:element name="segment" type="segment"/>
    <xs:element name="outType" type="xs:string"/>
    <xs:element name="messages" type="messages"/>
    <xs:element name="message" type="message"/>
    <xs:element name="inType" type="xs:string"/>
    <xs:element name="fields" type="fields"/>
    <xs:element name="field" type="field"/>
    <xs:element name="faults" type="faults"/>
    <xs:element name="faultInternalMessage" type="xs:string"/>
    <xs:element name="faultInternalCode" type="xs:string"/>
    <xs:element name="faultExternalCode" type="xs:string"/>
    <xs:element name="faultExternalMessage" type="xs:string"/>
    <xs:element name="segmentName" type="xs:string"/>
    <xs:element name="fieldNumber" type="xs:string"/>
    <xs:element name="componentNumber" type="xs:string"/>
    <xs:element name="fault" type="fault"/>
    <xs:element name="dataTypes" type="dataTypes"/>
    <xs:element name="dataType" type="dataType"/>
    <xs:element name="customerId" type="customerId"/>
    <xs:element name="configuration" type="configuration"/>
    <xs:element name="application" type="application"/>
    <xs:element name="ackPrecedenceType" type="xs:string"/>
    <xs:element name="ackNumOfLevels" type="xs:int"/>
</xs:schema>

=== basavesht/javaee-work-projects/bosch/standard-adapter/WEB-INF/classes/StandardAdapterConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!--
    Document   : StandardAdapterConfiguration.xml
    Created on : Sep 06, 2012, 3.24 AM
    Author     : tis1pal
    Description: Configuration File for validations and runtime values
	-->
<iv:configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:iv="http://integration.tmp.bosch.com/validation" xsi:schemaLocation="http://integration.tmp.bosch.com/validation IntegrationConfiguration.xsd">
    <iv:messages>
		<!-- Configuration For ADT_A04 Message -->
        <iv:message iv:id="ADT_A04">
			<!-- Configuration For Required segments in a ADT_A04 Message -->
            <iv:segments>

				<!-- Configuration For PID in ADT_A04 Message -->
                <iv:segment iv:id="PID">
                    <iv:validations>
                        <iv:validation iv:type="MANDATORY">
                            <iv:value>true</iv:value>
                            <iv:fault>
                                <iv:faultInternalCode>SIA_PID_20</iv:faultInternalCode>
                                <iv:faultInternalMessage>Missing PID Segment</iv:faultInternalMessage>
                                <iv:faultExternalCode>SIA_PID_20</iv:faultExternalCode>
                                <iv:faultExternalMessage>Missing PID Segment</iv:faultExternalMessage>
                                <iv:segmentName>PID</iv:segmentName>
                                <iv:fieldNumber>0</iv:fieldNumber>
                                <iv:componentNumber>0</iv:componentNumber>
                            </iv:fault>
                        </iv:validation>
						<!--Check if all of the following ID codes Exist in PID3 fields -->
                        <iv:validation iv:type="MISSING_IDENTIFIER">
                            <iv:value>true</iv:value>
                            <iv:faults>
                                <iv:fault iv:id="PS">
                                    <iv:faultInternalCode>SIA_PID_400</iv:faultInternalCode>
                                    <iv:faultInternalMessage>Missing Patient System ID</iv:faultInternalMessage>
                                    <iv:faultExternalCode>SIA_PID_400</iv:faultExternalCode>
                                    <iv:faultExternalMessage>Missing Patient System ID</iv:faultExternalMessage>
                                    <iv:segmentName>PID</iv:segmentName>
                                    <iv:fieldNumber>3</iv:fieldNumber>
                                    <iv:componentNumber>1</iv:componentNumber>
                                </iv:fault>
                                <iv:fault iv:id="SS">
                                    <iv:faultInternalCode>SIA_PID_410</iv:faultInternalCode>
                                    <iv:faultInternalMessage>SSN is Missing</iv:faultInternalMessage>
                                    <iv:faultExternalCode>SIA_PID_410</iv:faultExternalCode>
                                    <iv:faultExternalMessage>Missing SSN</iv:faultExternalMessage>
                                    <iv:segmentName>PID</iv:segmentName>
                                    <iv:fieldNumber>3</iv:fieldNumber>
                                    <iv:componentNumber>1</iv:componentNumber>
                                </iv:fault> 
                            </iv:faults>
                        </iv:validation>
                    </iv:validations>
				    <iv:fields>
                        <!--Validation for PID5 containing patient last name-->
                        <iv:field iv:id="PID5">
                            <iv:validations>
                                <iv:validation iv:type="MANDATORY">
                                    <iv:value>true</iv:value>
                                    <iv:fault>
                                        <iv:faultInternalCode>SIA_PID_420</iv:faultInternalCode>
                                        <iv:faultInternalMessage>Missing PID5 Segment</iv:faultInternalMessage>
                                        <iv:faultExternalCode>SIA_PID_420</iv:faultExternalCode>
                                        <iv:faultExternalMessage>Missing Last Name</iv:faultExternalMessage>
                                        <iv:segmentName>PID</iv:segmentName>
                                        <iv:fieldNumber>5</iv:fieldNumber>
                                        <iv:componentNumber>0</iv:componentNumber>
                                    </iv:fault>
                                </iv:validation>
                            </iv:validations>
                            <iv:dataTypes>
								<!-- Validating the Last Name which is present in pid5.xpn1.fn1-->
                                <iv:dataType iv:id="XPN1_FN1">
                                    <iv:validations>
                                        <iv:validation iv:type="MANDATORY">
                                            <iv:value>true</iv:value>
                                            <iv:fault>
                                                <iv:faultInternalCode>SIA_PID_420</iv:faultInternalCode>
                                                <iv:faultInternalMessage>LastName is missing</iv:faultInternalMessage>
                                                <iv:faultExternalCode>SIA_PID_420</iv:faultExternalCode>
                                                <iv:faultExternalMessage>Missing Last Name</iv:faultExternalMessage>
                                                <iv:segmentName>PID</iv:segmentName>
                                                <iv:fieldNumber>5</iv:fieldNumber>
                                                <iv:componentNumber>1</iv:componentNumber>
                                            </iv:fault>
                                        </iv:validation>
                                  </iv:validations>
                                </iv:dataType>
                           </iv:dataTypes>
                       </iv:field>
                        	<!--Validation for PID7 containing patient DOB-->
                        <iv:field iv:id="PID7">
                            <iv:validations>
                                <iv:validation iv:type="MANDATORY">
                                    <iv:value>true</iv:value>
                                    <iv:fault>
                                        <iv:faultInternalCode>SIA_PID_430</iv:faultInternalCode>
                                        <iv:faultInternalMessage>Missing PID7 Segment</iv:faultInternalMessage>
                                        <iv:faultExternalCode>SIA_PID_430</iv:faultExternalCode>
                                        <iv:faultExternalMessage>Missing DOB</iv:faultExternalMessage>
                                        <iv:segmentName>PID</iv:segmentName>
                                        <iv:fieldNumber>7</iv:fieldNumber>
                                        <iv:componentNumber>0</iv:componentNumber>
                                    </iv:fault>
                                </iv:validation>
                            </iv:validations>
                            <iv:dataTypes>
								<!--Validation for TS1 which contains date of birth -->
                                <iv:dataType iv:id="TS1">
                                    <iv:validations>
                                        <iv:validation iv:type="MANDATORY">
                                            <iv:value>true</iv:value>
                                            <iv:fault>
                                                <iv:faultInternalCode>SIA_PID_430</iv:faultInternalCode>
                                                <iv:faultInternalMessage>Missing DOB</iv:faultInternalMessage>
                                                <iv:faultExternalCode>SIA_PID_430</iv:faultExternalCode>
                                                <iv:faultExternalMessage>Missing DOB</iv:faultExternalMessage>
                                                <iv:segmentName>PID</iv:segmentName>
                                                <iv:fieldNumber>7</iv:fieldNumber>
                                                <iv:componentNumber>1</iv:componentNumber>
                                            </iv:fault>
                                        </iv:validation>
                                    </iv:validations>
                                </iv:dataType>
                            </iv:dataTypes>
                        </iv:field>
                     </iv:fields>
                </iv:segment>
				<!--
 Configuration For EVN in ADT_A04 Message
                  EVN fields are not validated in ADT_A04 message for SA
				-->
                <iv:segment iv:id="EVN">
                    <iv:validations>
                        <iv:validation iv:type="MANDATORY">
                            <iv:value>true</iv:value>
                            <iv:fault>
                                <iv:faultInternalCode>SIA_EVN_40</iv:faultInternalCode>
                                <iv:faultInternalMessage>Missing EVN Segment</iv:faultInternalMessage>
                                <iv:faultExternalCode>SIA_EVN_40</iv:faultExternalCode>
                                <iv:faultExternalMessage>Missing EVN Segment</iv:faultExternalMessage>
                                <iv:segmentName>EVN</iv:segmentName>
                                <iv:fieldNumber>0</iv:fieldNumber>
                                <iv:componentNumber>0</iv:componentNumber>
                            </iv:fault>
                        </iv:validation>
                    </iv:validations>
                </iv:segment>
				<!--Configuration For PV1 in ADT_A04 Message -->
                <iv:segment iv:id="PV1">
                    <iv:validations>
                        <iv:validation iv:type="MANDATORY">
                            <iv:value>true</iv:value>
                            <iv:fault>
